# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
        BASE_URL: /
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install
      run: npm install
    - name: CI
      run: npm ci
    - name: Build
      run: npm run build
    - name: Copy
      run: cp dist/index.html dist/404.html

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4.4.1
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: dist